# Generated by Django 4.2.6 on 2023-10-18 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fertilizers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fertilizer_name', models.CharField(max_length=255)),
                ('price_per_kg', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Fertilizers',
                'verbose_name_plural': 'Fertilizers',
                'db_table': 'Fertilizers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Shop_Details',
            fields=[
                ('shop_id', models.CharField(primary_key=True, serialize=False)),
                ('shop_phone', models.CharField()),
                ('district', models.CharField()),
                ('shop_name', models.CharField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('distance', models.CharField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Shop_Details',
                'verbose_name_plural': 'Shop_Details',
                'db_table': 'Shop_Details',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField()),
                ('customer_phone', models.CharField()),
                ('total_price', models.CharField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('fertilizers', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.fertilizers')),
            ],
            options={
                'verbose_name': 'Orders',
                'verbose_name_plural': 'Orders',
                'db_table': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Ordered_Fertilizers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('fertilizer_total_price', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('fertilizers', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.fertilizers')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.orders')),
            ],
        ),
    ]
