# Generated by Django 4.2.6 on 2023-10-18 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_orders_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='fertilizers',
        ),
    ]
