# Generated by Django 4.2.6 on 2023-10-18 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_orders_fertilizers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordered_fertilizers',
            options={'ordering': ['-created_at'], 'verbose_name': 'Ordered_Fertilizers', 'verbose_name_plural': 'Ordered_Fertilizers'},
        ),
        migrations.AlterModelTable(
            name='ordered_fertilizers',
            table='Ordered_Fertilizers',
        ),
    ]
