# Generated by Django 4.2.6 on 2023-10-18 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_ordered_fertilizers_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.shop_details'),
        ),
    ]
